/** Linux workaround for ASRT mandatory-deny mount placeholders in git commands. */

import { spawnSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { chmodSync, lstatSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import * as path from "node:path";
import { DANGEROUS_FILES, getDangerousDirectories } from "@foxfirecodes/sandbox-runtime/dist/sandbox/sandbox-utils.js";

/**
 * Inject a generated git excludes file into the sandboxed shell environment.
 *
 * ASRT's Linux backend may create mandatory-deny mount-point placeholders in
 * the writable cwd. Those placeholders are intentionally visible inside the
 * sandbox, so git commands run by any tool (`git`, `but`, npm scripts, etc.)
 * must inherit a global exclude that hides the exact ASRT-protected names.
 */
export function withSandboxGitExcludes(
	command: string,
	cwd: string,
	platform: NodeJS.Platform = process.platform,
): string {
	if (!isLinuxPlatform(platform)) return command;
	if (!shouldInjectSandboxGitExcludes(cwd)) return command;
	const excludeFile = ensureSandboxGitExcludesFile(cwd);
	const existingCount = parseGitConfigCount(process.env.GIT_CONFIG_COUNT);
	const assignments = [
		["GIT_CONFIG_COUNT", String(existingCount + 1)],
		[`GIT_CONFIG_KEY_${existingCount}`, "core.excludesFile"],
		[`GIT_CONFIG_VALUE_${existingCount}`, excludeFile],
	] as const;
	const exports = assignments
		.map(([key, value]) => `export ${key}=${shellSingleQuote(value)}`)
		.join("\n");
	// ASRT keys violation annotations by a truncated encoding of the command it
	// receives. Put a per-command no-op marker before the common export prelude so
	// different sandboxed commands do not collide in ASRT's violation store.
	const annotationKey = createHash("sha256").update(command).digest("hex").slice(0, 16);
	return `: ${shellSingleQuote(`pi-auto-asrt-key ${annotationKey}`)}\n${exports}\n${command}`;
}

export function getAsrtMandatoryDenyGitExcludePatterns(): string[] {
	return getAsrtMandatoryDenyPathPatterns().filter((p) => !p.startsWith(".git/"));
}

/** Shared by Linux denial detection and retry-reason path extraction. */
export function getAsrtMandatoryDenyPathPatterns(): string[] {
	return [...DANGEROUS_FILES, ...getDangerousDirectories(), ".git/hooks", ".git/config"].map((p) => p.replace(/^\.\//, ""));
}

function ensureSandboxGitExcludesFile(cwd: string): string {
	const hash = createHash("sha256").update(path.resolve(cwd)).digest("hex").slice(0, 16);
	const dir = mkdtempSync(path.join(tmpdir(), "pi-auto-sandbox-git-excludes-"));
	chmodSync(dir, 0o700);
	const filePath = path.join(dir, `${hash}-${randomUUID()}.gitignore`);
	writeFileSync(filePath, buildSandboxGitExcludesFileContent(cwd), {
		encoding: "utf8",
		flag: "wx",
		mode: 0o600,
	});
	chmodSync(filePath, 0o600);
	return filePath;
}

function buildSandboxGitExcludesFileContent(cwd: string): string {
	const existing = readExistingGitExcludeContents(cwd);
	const mandatory = getAsrtMandatoryDenyGitExcludePatterns().join("\n");
	return [
		"# Generated by pi-auto for sandboxed commands.",
		"# Keeps ASRT mandatory-deny mount-point placeholders out of git status/add.",
		mandatory,
		existing ? "\n# Existing user/global core.excludesFile content follows." : "",
		existing,
		"",
	]
		.filter((part) => part.length > 0)
		.join("\n");
}

function readExistingGitExcludeContents(_cwd: string): string {
	// Do not read custom core.excludesFile contents here. Repository-local config
	// is untrusted and could point core.excludesFile at a sensitive host file.
	// withSandboxGitExcludes skips the injection entirely when git reports a
	// custom effective excludes path, preserving the user's ignore semantics
	// instead of copying host file contents into a sandbox-visible temp file.
	const existing = readNonSymlinkTextFile(defaultGitExcludesFilePath());
	return existing?.trim() ?? "";
}

function shouldInjectSandboxGitExcludes(cwd: string): boolean {
	const configured = readConfiguredGitExcludesFilePath(cwd);
	if (!configured) return true;
	return isSamePath(configured, defaultGitExcludesFilePath());
}

function readConfiguredGitExcludesFilePath(cwd: string): string | undefined {
	const fromEnv = readConfiguredGitExcludesFilePathFromEnv();
	if (fromEnv) return fromEnv;
	try {
		const result = spawnSync("git", ["config", "--path", "--get", "core.excludesFile"], {
			cwd,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		});
		if (result.status !== 0 || typeof result.stdout !== "string") return undefined;
		const out = result.stdout.trim();
		return out.length > 0 ? out : undefined;
	} catch {
		return undefined;
	}
}

function readConfiguredGitExcludesFilePathFromEnv(): string | undefined {
	const count = parseGitConfigCount(process.env.GIT_CONFIG_COUNT);
	for (let i = 0; i < count; i++) {
		const key = process.env[`GIT_CONFIG_KEY_${i}`]?.toLowerCase();
		if (key !== "core.excludesfile") continue;
		const value = process.env[`GIT_CONFIG_VALUE_${i}`]?.trim();
		return value || undefined;
	}
	return undefined;
}

function isSamePath(a: string, b: string): boolean {
	return path.resolve(a) === path.resolve(b);
}

function defaultGitExcludesFilePath(): string {
	const xdgConfigHome = process.env.XDG_CONFIG_HOME || path.join(homedir(), ".config");
	return path.join(xdgConfigHome, "git", "ignore");
}

function readNonSymlinkTextFile(filePath: string): string | undefined {
	try {
		const stat = lstatSync(filePath);
		if (!stat.isFile() || stat.isSymbolicLink()) return undefined;
		return readFileSync(filePath, "utf8");
	} catch {
		// Best-effort only. Losing user excludes here is less bad than failing
		// every sandboxed bash command because an ignore file is unreadable.
		return undefined;
	}
}

function parseGitConfigCount(raw: string | undefined): number {
	if (!raw) return 0;
	const parsed = Number.parseInt(raw, 10);
	return Number.isInteger(parsed) && parsed >= 0 ? parsed : 0;
}

function shellSingleQuote(value: string): string {
	return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function isLinuxPlatform(platform: NodeJS.Platform = process.platform): boolean {
	return platform === "linux";
}
